version: '3.4'

services:
  dev:
    image: dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:808 --nothreading --noreload"]
    ports:
      - 808:808
      - 5678:5678
