# Generated by Django 4.0.7 on 2022-09-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_holistech', models.CharField(max_length=6)),
                ('machine_ipaddr', models.CharField(max_length=15)),
                ('machine_hostname', models.CharField(max_length=253)),
                ('machine_fisname', models.CharField(max_length=24)),
                ('machine_area', models.CharField(choices=[('SMT', 'SMT'), ('CBA', 'CBA'), ('FA', 'FA'), ('AUDI', 'AUDI'), ('GEN4', 'GEN4')], max_length=10)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
