# Generated by Django 4.1.1 on 2022-09-16 06:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=10)),
                ('modify_date', models.DateTimeField(blank=True)),
                ('sizes', models.CharField(max_length=50)),
                ('paths', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=250)),
                ('backupType', models.CharField(max_length=30)),
                ('size_MB', models.DecimalField(decimal_places=2, max_digits=250)),
                ('date', models.CharField(max_length=250)),
                ('extension', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('machine_holistech', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('machine_ipaddr', models.CharField(max_length=15)),
                ('machine_hostname', models.CharField(max_length=253)),
                ('machine_fisname', models.CharField(max_length=24)),
                ('machine_area', models.CharField(choices=[('SMT', 'SMT'), ('CBA', 'CBA'), ('FA', 'FA'), ('AUDI', 'AUDI'), ('GEN4', 'GEN4')], max_length=10)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='requestBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestBackup_reason', models.CharField(max_length=250)),
                ('requestBackup_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('requestBackup_status', models.CharField(blank=True, choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('DONE', 'Done')], default='REQUESTED', max_length=10)),
                ('requestor', models.CharField(default='', max_length=100)),
                ('requestBackup_holistech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.machine')),
            ],
        ),
    ]
