# Generated by Django 4.0.7 on 2022-09-01 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_holistech', models.CharField(max_length=6, unique=True)),
                ('machine_ipaddr', models.CharField(max_length=15)),
                ('machine_hostname', models.CharField(max_length=253)),
                ('machine_fisname', models.CharField(max_length=24)),
                ('machine_area', models.CharField(choices=[('SMT', 'SMT'), ('CBA', 'CBA'), ('FA', 'FA'), ('AUDI', 'AUDI'), ('GEN4', 'GEN4')], max_length=10)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='requestBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestBackup_reason', models.CharField(max_length=250)),
                ('requestBackup_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 2, 1, 6, 12, 534279))),
                ('requestBackup_holistech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.machine')),
            ],
        ),
    ]
