# Generated by Django 4.0.7 on 2022-09-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_holistech',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
