# Generated by Django 4.1.1 on 2022-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restoredBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoredBackup_jiraId', models.CharField(max_length=10)),
                ('restoredBackup_holistech', models.CharField(max_length=6)),
                ('restoredBackup_hostname', models.CharField(max_length=250)),
                ('restoredBackup_backup', models.CharField(max_length=250)),
                ('restoredBackup_restoreDate', models.DateTimeField(auto_now_add=True)),
                ('restoredBackup_creator', models.CharField(max_length=100)),
            ],
        ),
    ]
