# Generated by Django 4.0.7 on 2022-09-05 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbackup',
            name='requestor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestbackup',
            name='requestBackup_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 5, 8, 31, 12, 215619)),
        ),
    ]
