# Generated by Django 4.0.7 on 2022-09-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_requestbackup_requestor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestbackup',
            old_name='requestBAckup_status',
            new_name='requestBackup_status',
        ),
        migrations.AlterField(
            model_name='requestbackup',
            name='requestBackup_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
