# Generated by Django 4.0.7 on 2022-09-01 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_alter_machine_machine_holistech'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestBackup_reason', models.CharField(max_length=250)),
                ('requestBackup_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 1, 13, 39, 31, 266154))),
                ('requestBackup_holistech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.machine')),
            ],
        ),
    ]
