# Generated by Django 4.0.7 on 2022-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_rename_requestbackup_status_requestbackup_requestbackup_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='backups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=250)),
                ('version', models.CharField(max_length=10)),
                ('modify_date', models.DateTimeField(blank=True)),
                ('sizes', models.CharField(max_length=50)),
                ('paths', models.CharField(max_length=250)),
            ],
        ),
    ]
