# Generated by Django 4.0.7 on 2022-09-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backups'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=250)),
                ('backupType', models.CharField(max_length=30)),
                ('size_MB', models.DecimalField(decimal_places=2, max_digits=250)),
                ('date', models.CharField(max_length=250)),
                ('extension', models.CharField(max_length=250)),
            ],
        ),
    ]
